server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_blog?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&nullCatalogMeansCurrent=true&allowMultiQueries=true
    username: root
    password: 1234
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 15
      max-wait: 5000
      time-between-eviction-runs-millis: 90000
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  thymeleaf:
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      encoding: utf-8
      cache: false

  aop:
    auto: true
    proxy-target-class: true

  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb



logging:
  level:
    com.wip.dao: DEBUG



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wip.model

swagger:
  show: true
#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  retrunPageInfo: check
